export const LOCAL_CONN_START       = 'LOCAL_CONN_START';
export const DATA_CHANNEL_CREATE    = 'DATA_CHANNEL_CREATE';
export const DATA_CHANNEL_OPEN      = 'DATA_CHANNEL_OPEN';
export const DATA_CHANNEL_CLOSE     = 'DATA_CHANNEL_CLOSE';
export const REMOTE_CONN_START      = 'REMOTE_CONN_START';
export const REMOTE_DATA_CHANNEL_OK = 'REMOTE_DATA_CHANNEL_OK';
